/my/init/field/name data/field.root
/my/init/detector/tpc
/my/init/detector/bar

#############################################

/run/initialize

/analysis/verbose 1

#############################################

/my/pga/gun
/my/pga/vertex  0 -205 -13.25 mm
/my/pga/energy1 1000 MeV
/my/pga/energy2 3000 MeV
/my/pga/phi1    179.99 deg
/my/pga/phi2    180.01 deg
/my/pga/theta1  89.999 deg
/my/pga/theta2  90.001 deg

#############################################

/analysis/setFileName data/run_test_neutron
#
/my/pga/name neutron
#
/run/printProgress 10
/run/beamOn 200
