/my/init/field/name data/field.root
/my/init/detector/tpc
/my/init/detector/bar

#############################################

/run/initialize

/analysis/verbose 1

#############################################

/gps/position 0 -205 -13.25 mm
#
/gps/ang/type iso
/gps/ang/mintheta 90 deg
/gps/ang/maxtheta 160 deg
/gps/ang/minphi 179.99 deg
/gps/ang/maxphi 180.01 deg
#
/gps/ene/type Lin
/gps/ene/min 100 MeV
/gps/ene/max 3000 MeV
/gps/ene/intercept 100
/gps/ene/gradient 0

#############################################

/analysis/setFileName data/run_test_neutron
#
/gps/particle neutron
#
/run/printProgress 2000
/run/beamOn 20000

#############################################

/analysis/setFileName data/run_test_proton
#
/gps/particle proton
#
#/gps/ene/type Mono
#/gps/direction 0.64278761 0 0.76604444
#
/run/printProgress 2000
/run/beamOn 20000
