/my/init/detector/tpc
/my/init/detector/bar
#/my/init/detector/bar0
#/my/init/detector/wall

#field
/my/init/field/name data/field.root

#initialize run
/run/initialize

# create viewer draw volumes
/vis/open OGL 600x600-0+0
/vis/drawVolume

# print event process status
/vis/verbose warnings 

# print tracking status
/tracking/verbose 1

# draw volumes in surface style
/vis/viewer/set/style surface
/vis/viewer/set/viewpointVector 0.5 1 0.5

# draw in perspective
/vis/viewer/set/projection perspective 10 deg

# draw axes
/vis/scene/add/axes 0 0 0 400 mm

# set background colour
/vis/viewer/set/background white

# draw trajectory (smooth / rich)
/vis/scene/add/trajectories smooth

# draw step points
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

# draw all events when multiple events are simulated at once
/vis/scene/endOfEventAction accumulate

# 1111111111111111111111111111111111111111
# gps
#/gps/position  0 -205 -13.24 mm
#/gps/particle  neutron
##
#/gps/ang/type iso
#/gps/ang/mintheta 90 deg
#/gps/ang/maxtheta 160 deg
#/gps/ang/minphi 179.99 deg
#/gps/ang/maxphi 180.01 deg
##
#/gps/ene/type Lin
#/gps/ene/min 100 MeV
#/gps/ene/max 3000 MeV
#/gps/ene/intercept 100
#/gps/ene/gradient 0
#
##analysis
#/analysis/verbose 1
#/analysis/setFileName data/vis_test
#
## run
#/run/beamOn 200
# 1111111111111111111111111111111111111111

# 2222222222222222222222222222222222222222
/analysis/verbose 1
/analysis/setFileName data/vis_test
#
/my/pga/gun
/my/pga/vertex  0 -205 -13.25 mm
/my/pga/energy1 1000 MeV
/my/pga/energy2 3000 MeV
/my/pga/phi1    179.99 deg
/my/pga/phi2    180.01 deg
/my/pga/theta1  89.999 deg
/my/pga/theta2  90.001 deg
#
/run/beamOn 100
# 2222222222222222222222222222222222222222
